arb-dir: lib/src/core/constant/localization/translations
template-arb-file: intl_en.arb
output-localization-file: app_localization.dart
synthetic-package: false
output-dir: lib/src/core/constant/localization
output-class: AppLocalization