name: rick_and_morty
description: Production-ready template for Flutter applications.
# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  flutter_localizations:
    sdk: flutter

  # Networking
  http: ^1.2.2
  cronet_http: ^1.3.2
  cupertino_http: ^2.0.0

  # Storing data
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Logging
  stack_trace: ^1.11.1
  sentry_flutter: ^8.7.0

  # State Management
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2

  # Navigation
  auto_route: ^9.2.2

  # Utils
  platform_info: ^5.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  intercepted_client: ^0.0.1
  clock: ^1.1.1
  json_annotation: ^4.9.0
  pure: ^0.3.0

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  provider: ^6.1.2

dev_dependencies:
  # Testing
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  # Lints
  sizzle_lints: ^2.1.3

  # Utils
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  # Codegen
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1+1
  dart_code_metrics_presets: ^2.16.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/icons/gender/
    - assets/icons/species/
    - assets/icons/live_status/
    - assets/icons/common/

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80
